knp_doctrine_behaviors:
    timestampable:  true
    blameable:      false
    geocodable:     false
    loggable:       false
    sluggable:      false
    soft_deletable: false
    # All others behaviors are disabled