easy_admin:
    design:
        assets:
            css:
                - '/css/modal.css'
                - '/css/tabs.css'
                - '/css/admin.css'
            js:
                - '/js/modal.js'
                - '/js/tabs.js'
                - '/js/media.js'
        form_theme:
            - 'horizontal'
            - 'form/custom_layout.html.twig'
    entities:
        Article:
            class: App\Entity\Article
            form:
                fields:
                    - { property: title }
                    - { property: headImage, type: 'App\Form\Type\AddOrChooseImageType', label: 'Image' }
        Image:
            class: App\Entity\Image
            controller: App\Controller\ImageController
            list:
                fields:
                    - title
                    - { property: 'image', template: 'EasyAdmin/Image/list/image.html.twig' }
            form:
                fields:
                    - title
                    - { property: 'imageFile', type: 'file' }
        Event:
            class: App\Entity\Event
            list:
                fields: ['id', 'title']
            form:
                fields:
                    - { property: title }
                    - date
                    - { property: headBandImage, type: 'App\Form\Type\AddOrChooseImageType', label: 'Image' }
