easy_admin:
    design:
        assets:
            css:
                - '/build/admin.css'
                - '/css/modal.css'  # Used for media popin
                - '/css/tabs.css'   # Used for media popin
                - '/css/admin.css'
            js:
                - '/build/admin.js'
                - '/js/modal.js'    # Used for media popin
                - '/js/tabs.js'     # Used for media popin
                - '/js/media.js'
                - '/bundles/lchseo/js/seo.js'
        form_theme:
            - 'horizontal'
            - 'form/media.html.twig'
            - '@LchSeoBundle/form/fields.html.twig'
        menu:
            - { label: 'admin.menu.dashboard', route: 'admin_dashboard', default: true }
            - { entity: 'Post', label: 'admin.menu.post' }
            - { entity: 'Image', label: 'admin.menu.image' }
#            - { entity: 'Event', label: 'admin.menu.event' }
    entities:
        Post:
            class: App\Entity\Editorial\Post
            list:
              - { property: id }
              - { property: title }
              - { property: status }
            form:
              fields:
                - { type: 'group', css_class: 'col-xs-9', label: 'admin.post.general.title' }
                - { property: title }
                - { type: 'group', css_class: 'col-xs-3', label: 'admin.post.status.title' }
                - { property: status, type: 'choice', type_options: {choices: { draft: draft, published: published } } }
                - { type: 'group', css_class: 'col-xs-3 pull-right', label: 'admin.post.image.title' }
                - { property: headImage, type: 'App\Form\Type\AddOrChooseImageType', label: 'Image' }
                - { type: 'group', css_class: 'col-xs-12', label: 'admin.post.seo.title' }
                - { property: slug, type: 'Lch\SeoBundle\Form\SlugType' }
                - { property: seoTitle, type: 'text' }
                - { property: seoDescription, type: 'text' }

#        Article:
#            class: App\Entity\Article
#            controller: App\Controller\Admin\ArticleController
#            templates:
#                list: '@App\admin\article\list.html.twig'
#            list:
#                fields:
#                    - { property: id }
#                    - { property: title }
#                    - { property: published }
#            form:
#                fields:
#                    - { property: title }
#                    - { property: headImage, type: 'App\Form\Type\AddOrChooseImageType', label: 'Image' }
#                    - { property: published, type_options: { required: false } }
#                    - { property: content }
#            search:
#                fields:
#                   - { property: 'title', searchField: 'title' }
#                   - { property: 'published', searchField: 'status'}
        Image:
            class: App\Entity\Media\Image
            controller: App\Controller\Media\Admin\ImageController
            list:
                title: 'admin.image.list.title'
                actions:
                    - { name: 'edit', label: 'admin.action.edit.label' }
                    - { name: 'download', label: 'media.action.download.label' }
                    - { name: 'delete', label: 'admin.action.delete.label' }
                fields:
                    - { property: 'title', label: 'media.image.title.label' }
                    - { property: 'image', template: 'EasyAdmin/Image/list/image.html.twig', label: 'media.image.image.label' }
            form:
                fields:
                    - title
                    - { property: 'file', type: 'file' }
        Event:
            class: App\Entity\Event
            list:
                fields: ['id', 'title']
            form:
                fields:
                    - { property: title }
                    - date
                    - { property: headBandImage, type: 'App\Form\Type\AddOrChooseImageType', label: 'Image' }
