easy_admin:
    design:
        assets:
            css:
                - '/css/modal.css'  # Used for media popin
                - '/css/tabs.css'   # Used for media popin
                - '/css/admin.css'
            js:
                - '/js/modal.js'    # Used for media popin
                - '/js/tabs.js'     # Used for media popin
                - '/js/media.js'
        form_theme:
            - 'horizontal'
            - 'form/media.html.twig'
    entities:
        Article:
            class: App\Entity\Article
            list:
                fields:
                    - { property: id}
                    - { property: title }
            form:
                fields:
                    - { property: title }
                    - { property: headImage, type: 'App\Form\Type\AddOrChooseImageType', label: 'Image' }
        Image:
            class: App\Entity\Media\Image
            controller: App\Controller\ImageController
            list:
                actions: ['edit', 'download', 'delete']
                fields:
                    - title
                    - { property: 'image', template: 'EasyAdmin/Image/list/image.html.twig' }
            form:
                fields:
                    - title
                    - { property: 'file', type: 'file' }
        Event:
            class: App\Entity\Event
            list:
                fields: ['id', 'title']
            form:
                fields:
                    - { property: title }
                    - date
                    - { property: headBandImage, type: 'App\Form\Type\AddOrChooseImageType', label: 'Image' }
