easy_admin:
    design:
        assets:
            css:
                - '/css/modal.css'
                - '/css/tabs.css'
                - '/css/admin.css'
            js:
                - '/js/modal.js'
                - '/js/tabs.js'
                - '/js/media.js'
        form_theme:
            - 'horizontal'
            - 'form/custom_layout.html.twig'
    entities:
        Image:
            class: App\Entity\Image
            controller: App\Controller\ImageController
            form:
                fields:
                    - title
                    - { property: 'imageFile', type: 'file' }
        Event:
            class: App\Entity\Event
            list:
                fields: ['id', 'title']
            form:
                fields:
                    - { property: title }
                    - date
                    - { property: headBandImage, type_options: { block_name: 'head_band_image' } }
