index:
    path: /
    defaults: { _controller: 'App\Controller\MainController::index' }

app_front:
  resource: "routes/front-app.yaml"
  prefix:   /

app_back:
  resource: "routes/back-app.yaml"
  prefix:   /admin

cms_back:
  resource: "routes/back-cms.yaml"
  prefix:   /admin