<?php
/**
 * Created by PhpStorm.
 * User: nicolas
 * Date: 28/02/18
 * Time: 17:10
 */

namespace App\Controller\Admin\Editorial;

use App\Controller\Admin\BaseAdminController;

class PostController  extends BaseAdminController {

	public function editAction() {
		return parent::editAction(); // TODO: Change the autogenerated stub
	}
}